### PR TITLE
Fixes for simple-navigation 4 / Rails4

### PR DESCRIPTION
**Pull request by n-rodriguez**
This PR duplicates https://github.com/ShPakvel/simple_navigation_renderers/pull/12 and https://github.com/ShPakvel/simple_navigation_renderers/pull/13.
It fixes caret rendering and adds remove_navigation_class option.
It also fixes tests with Simple Navigation 4, RSpec new syntax and Rails  4 (html/document has been removed in Rails 4.2 and replaced by a gem rails-deprecated_sanitizer).

### CODE REVIEW

**Comment by n-rodriguez** [comment]
Ping!

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by n-rodriguez** [comment]
Up?

**Comment by n-rodriguez** [comment]
Hi there! Is there any chance to get this merged?

**Comment by n-rodriguez** [comment]
Up?

**Comment by n-rodriguez** [comment]
Up?

**Comment by vedsingh-fullstack** [comment]
can this be used with simple navigation 4?

**Comment by n-rodriguez** [comment]
@ved54321 yes

**Comment by n-rodriguez** [comment]
Almost a year of waiting... are you ok?

**Pull request closed without merging**
