### PR TITLE
added support for bootstrap 'navbar-text' element

### PR DESCRIPTION
**Pull request by sgbett**
adds a new menu item option :navbar_text which if set causes menu item to be rendered as a text link instead of a url and styled with navbar-text class as per http://getbootstrap.com/components/#navbar-text

``` ruby
SimpleNavigation::Configuration.run do |navigation|
  navigation.renderer = SimpleNavigationRenderers::Bootstrap3
  navigation.items do |primary|
    primary.item :sample_text, "Sample Text", navbar_text: true
  end
end
```

will produce...

``` html
<ul class="nav navbar-nav">
  <li>
    <p class="navbar-text">Sample Text</p>
  </li>
</ul>
```

### CODE REVIEW

**Comment by ShPakvel** [comment]
Hi.
I was thinking about the same when create this gem...
And I think it is not correct place for `navbar-text` to be located.

According bootstrap examples, there can be separate elements in navbar: `nav`, `form`, `button`, `text`. And I agree with that. There is no need for one of navigation item to look like text, except it is header.

And you can write a `text` element next to navigation menu like this:

``` erb
<div class="collapse navbar-collapse navbar-ex1-collapse">
  <%= render_navigation( expand_all: true ) %>
  <p class="navbar-text">Sample Text</p>
</div>
```

What do you think about it?

**Comment by sgbett** [comment]
I think that if bootstrap provides functionality, then the renderer should also provide it. So I agree it  should also provide support for all the items you suggest, however I didn't need those things yet so I just plucked the low hanging fruit - the `form` and `button` are probably more complicated.

In my use case, semantically, the navtexts are not headers, but just plain old text.

This is what my html looks like (decrufted):

``` html
<ul class="nav navbar-nav">
  <li><p class="navbar-text">Viewing</p></li>
  <li class="dropdown" id="pages">
    <a href="#" class="dropdown-toggle" data-target="#" data-toggle="dropdown">Options<b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li id="opt1"><a href="/1">1</a></li>
      <li id="opt2"><a href="/2">2</a></li>
    </ul>
  </li>
  <li><p class="navbar-text">for</p></li>
  <li class="dropdown" id="user">
    <a href="#" class="dropdown-toggle" data-target="#" data-toggle="dropdown">Your Account<b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li id="a"><a href="/a">A</a></li>
      <li id="b"><a href="/b">B</a></li>
    </ul>
  </li>
</ul>
```

Yes I can hand write the html for the menu, but that rather defeats the purpose of using both simple_navigation and this gem. The above html is now trivially achievable by just specifying `navbar_text: true` on the relevant menu item.

If you have a preferred way to implement this functionality then thats cool with me. Or if their is some problem with the way I have implemented I'd like to know. This is the first time I have ever done a pull request for anything!

**Comment by andi** [comment]
I usually like the idea of incremental additions :-) So no harm in "just" adding that. But your pull request breaks the travis build (https://travis-ci.org/ShPakvel/simple_navigation_renderers/builds/19665439). But of course it Pavel's decision on how to proceed. Maybe you should also check out https://github.com/pdf/simple-navigation-bootstrap. Don't know the current state of that one, but maybe it would be worth thinking about merging the efforts...

**Comment by sgbett** [comment]
So it does. My first question is "What's a travis?" ;)

Anyway I googled around and figured it out. I looked at the build logs, and there was a sea of red! Maybe I'm missing something obvious but, bearing in mind my naivety to the whole process,  I'm not sure how my change has broken so much stuff? Sorry if this is a silly question :)

**Comment by sgbett** [comment]
OK so I'm thinking the fail is due to tests in simple_navigation failing due to them being for the standard renderer? Would that mean I need to submit a pull request to simple_navigation that makes those test conditional on the standard renderer being used? Or am I way off track here?

**Comment by ShPakvel** [comment]
I will look at specs closer a bit later.

**Comment by ShPakvel** [comment]
Hi there.
Sorry, I was really busy to answer earlier.

I've added `navbar-text` option.

Notes that I've changed the previous code a bit too: I've separated `divider` option see example from [Readme](https://github.com/ShPakvel/simple_navigation_renderers/blob/master/README.md).

I have not add more concise glyphicon specification because it is only for Bootstrap 3. As you can read in Readme, icon option was created to provide any kind of icons.
Bootstrap 2 use `icon-book` format.
Bootstrap 3 use `glyphicon-book` format.
FontAwesome 3 `icon-book` format
FontAwesome 4 `fa-book` format.
Custom format can be anything you wish like `my-custom-icon`.
As well, sometime you probably want to add special or custom class to some icon, and in this case you can also do it like `glyphicon glyphicon-book disabled my-custom-class and-the-third-one`.
And this is how icon option was created, just to take whole list of classes for icon.

Regarding broken specs.
The reason is new version of `simple-navigation`. Specifically, changes in `name_generator` method usage.

**Pull request closed without merging**
